version: '3.8'
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - ./reactjs.org/beta:/app
      - ./reactjs.org/beta/node_modules:/app/node_modules
    command: sh -c 'yarn dev'
    ports:
      - "3000:3000"
    stdin_open: true
  chatgpt:
    container_name: chatgpt
    build:
      context: .
      dockerfile: Dockerfile-chatGPT
    volumes:
      - ./chatGPT:/app
      - ./chatGPT/node_modules:/app/node_modules
      - ./reactjs.org/beta/src/content:/docs
    stdin_open: true
